general {
    no_focus_fallback = true
}

input {
    kb_layout = cz

    touchpad {
        natural_scroll = true
    }
}

# Windows closing by SUPER Q
unbind = SUPER, W
bind = SUPER, Q, killactive,

# Switch workspaces with CTRL + F[1-12]
unbind = CTRL, F1
unbind = CTRL, F2
unbind = CTRL, F3
unbind = CTRL, F4
unbind = CTRL, F5
unbind = CTRL, F6
unbind = CTRL, F7
unbind = CTRL, F8
unbind = CTRL, F9
unbind = CTRL, F10
unbind = CTRL, F11
unbind = CTRL, F12

bind = CTRL, F1, workspace, 1
bind = CTRL, F2, workspace, 2
bind = CTRL, F3, workspace, 3
bind = CTRL, F4, workspace, 4
bind = CTRL, F5, workspace, 5
bind = CTRL, F6, workspace, 6
bind = CTRL, F7, workspace, 7
bind = CTRL, F8, workspace, 8
bind = CTRL, F9, workspace, 9
bind = CTRL, F10, workspace, 10
bind = CTRL, F11, workspace, 11
bind = CTRL, F12, workspace, 12

# Move active window to a workspace with CTRL + SHIFT + F[1-12]
unbind = CTRL SHIFT, F1
unbind = CTRL SHIFT, F2
unbind = CTRL SHIFT, F3
unbind = CTRL SHIFT, F4
unbind = CTRL SHIFT, F5
unbind = CTRL SHIFT, F6
unbind = CTRL SHIFT, F7
unbind = CTRL SHIFT, F8
unbind = CTRL SHIFT, F9
unbind = CTRL SHIFT, F10
unbind = CTRL SHIFT, F11
unbind = CTRL SHIFT, F12

bind = CTRL SHIFT, F1, movetoworkspacesilent, 1
bind = CTRL SHIFT, F2, movetoworkspacesilent, 2
bind = CTRL SHIFT, F3, movetoworkspacesilent, 3
bind = CTRL SHIFT, F4, movetoworkspacesilent, 4
bind = CTRL SHIFT, F5, movetoworkspacesilent, 5
bind = CTRL SHIFT, F6, movetoworkspacesilent, 6
bind = CTRL SHIFT, F7, movetoworkspacesilent, 7
bind = CTRL SHIFT, F8, movetoworkspacesilent, 8
bind = CTRL SHIFT, F9, movetoworkspacesilent, 9
bind = CTRL SHIFT, F10, movetoworkspacesilent, 10
bind = CTRL SHIFT, F11, movetoworkspacesilent, 11
bind = CTRL SHIFT, F12, movetoworkspacesilent, 12

# Replace Hey email shortcut (SUPER SHITF + E) by files explorer
unbind = SUPER SHIFT, E
bind = SUPER SHIFT, E, exec, nautilus

# Alternative keys for brightness (WIN + PageUP / PageDown)
$osdclient = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"
bindel = SUPER, page_up,   exec, $osdclient --brightness raise
bindel = SUPER, page_down, exec, $osdclient --brightness lower

# Atlernative key for screenshot
bind = SUPER SHIFT, F4, exec, ~/.local/share/omarchy/bin/omarchy-cmd-screenshot

# Local overrides
source = ~/.config/hypr/local_overrides.conf
